/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { AppointmentServiceUpdateManyWithoutUsersInput } from "./AppointmentServiceUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { StaffServiceCustomUpdateManyWithoutUsersInput } from "./StaffServiceCustomUpdateManyWithoutUsersInput";
import { UserRoleUpdateManyWithoutUsersInput } from "./UserRoleUpdateManyWithoutUsersInput";
import { UserStaffTypeUpdateManyWithoutUsersInput } from "./UserStaffTypeUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  activo?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentServiceUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AppointmentServiceUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AppointmentServiceUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  appointmentServices?: AppointmentServiceUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaRegistro?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash?: string | null;

  @ApiProperty({
    required: false,
    type: () => StaffServiceCustomUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StaffServiceCustomUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StaffServiceCustomUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  staffServiceCustom?: StaffServiceCustomUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefono?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserRoleUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserRoleUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserRoleUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userRoles?: UserRoleUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserStaffTypeUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserStaffTypeUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserStaffTypeUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userStaffTypes?: UserStaffTypeUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
