/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { AppointmentService } from "../../appointmentService/base/AppointmentService";
import { Type } from "class-transformer";
import { StaffServiceCustom } from "../../staffServiceCustom/base/StaffServiceCustom";
import { UserRole } from "../../userRole/base/UserRole";
import { UserStaffType } from "../../userStaffType/base/UserStaffType";

@ObjectType()
class User {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  activo!: boolean | null;

  @ApiProperty({
    required: false,
    type: () => [AppointmentService],
  })
  @ValidateNested()
  @Type(() => AppointmentService)
  @IsOptional()
  appointmentServices?: Array<AppointmentService>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaRegistro!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash!: string | null;

  @ApiProperty({
    required: false,
    type: () => [StaffServiceCustom],
  })
  @ValidateNested()
  @Type(() => StaffServiceCustom)
  @IsOptional()
  staffServiceCustom?: Array<StaffServiceCustom>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefono!: string | null;

  @ApiProperty({
    required: false,
    type: () => [UserRole],
  })
  @ValidateNested()
  @Type(() => UserRole)
  @IsOptional()
  userRoles?: Array<UserRole>;

  @ApiProperty({
    required: false,
    type: () => [UserStaffType],
  })
  @ValidateNested()
  @Type(() => UserStaffType)
  @IsOptional()
  userStaffTypes?: Array<UserStaffType>;
}

export { User as User };
