/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentServiceCreateNestedManyWithoutAppointmentsInput } from "./AppointmentServiceCreateNestedManyWithoutAppointmentsInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ClientWhereUniqueInput } from "../../client/base/ClientWhereUniqueInput";
import { NotificationCreateNestedManyWithoutAppointmentsInput } from "./NotificationCreateNestedManyWithoutAppointmentsInput";
import { PaymentCreateNestedManyWithoutAppointmentsInput } from "./PaymentCreateNestedManyWithoutAppointmentsInput";

@InputType()
class AppointmentCreateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentServiceCreateNestedManyWithoutAppointmentsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentServiceCreateNestedManyWithoutAppointmentsInput)
  @IsOptional()
  @Field(() => AppointmentServiceCreateNestedManyWithoutAppointmentsInput, {
    nullable: true,
  })
  appointmentServices?: AppointmentServiceCreateNestedManyWithoutAppointmentsInput;

  @ApiProperty({
    required: true,
    type: () => ClientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientWhereUniqueInput)
  @Field(() => ClientWhereUniqueInput)
  clients!: ClientWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  estado?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaFin?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaInicio?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notas?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutAppointmentsInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutAppointmentsInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutAppointmentsInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutAppointmentsInput;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutAppointmentsInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutAppointmentsInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutAppointmentsInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutAppointmentsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;
}

export { AppointmentCreateInput as AppointmentCreateInput };
