/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
  IsInt,
  Max,
  IsNumber,
} from "class-validator";

import { AppointmentServiceItem } from "../../appointmentServiceItem/base/AppointmentServiceItem";
import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { ServiceStaffLink } from "../../serviceStaffLink/base/ServiceStaffLink";
import { StaffCustomService } from "../../staffCustomService/base/StaffCustomService";

@ObjectType()
class ServiceEntity {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  activo!: boolean | null;

  @ApiProperty({
    required: false,
    type: () => [AppointmentServiceItem],
  })
  @ValidateNested()
  @Type(() => AppointmentServiceItem)
  @IsOptional()
  appointmentServices?: Array<AppointmentServiceItem>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoria!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descripcion!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  duracionBaseMinutos!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  precioBase!: Decimal | null;

  @ApiProperty({
    required: false,
    type: () => [ServiceStaffLink],
  })
  @ValidateNested()
  @Type(() => ServiceStaffLink)
  @IsOptional()
  serviceStaffLinks?: Array<ServiceStaffLink>;

  @ApiProperty({
    required: false,
    type: () => [StaffCustomService],
  })
  @ValidateNested()
  @Type(() => StaffCustomService)
  @IsOptional()
  staffCustomServices?: Array<StaffCustomService>;
}

export { ServiceEntity as ServiceEntity };
