/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { AppointmentServiceItemListRelationFilter } from "../../appointmentServiceItem/base/AppointmentServiceItemListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { ServiceStaffLinkListRelationFilter } from "../../serviceStaffLink/base/ServiceStaffLinkListRelationFilter";
import { StaffCustomServiceListRelationFilter } from "../../staffCustomService/base/StaffCustomServiceListRelationFilter";

@InputType()
class ServiceEntityWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  activo?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => AppointmentServiceItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AppointmentServiceItemListRelationFilter)
  @IsOptional()
  @Field(() => AppointmentServiceItemListRelationFilter, {
    nullable: true,
  })
  appointmentServices?: AppointmentServiceItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  categoria?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  createdAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  descripcion?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  duracionBaseMinutos?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DecimalNullableFilter,
  })
  @Type(() => DecimalNullableFilter)
  @IsOptional()
  @Field(() => DecimalNullableFilter, {
    nullable: true,
  })
  precioBase?: DecimalNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ServiceStaffLinkListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ServiceStaffLinkListRelationFilter)
  @IsOptional()
  @Field(() => ServiceStaffLinkListRelationFilter, {
    nullable: true,
  })
  serviceStaffLinks?: ServiceStaffLinkListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => StaffCustomServiceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StaffCustomServiceListRelationFilter)
  @IsOptional()
  @Field(() => StaffCustomServiceListRelationFilter, {
    nullable: true,
  })
  staffCustomServices?: StaffCustomServiceListRelationFilter;
}

export { ServiceEntityWhereInput as ServiceEntityWhereInput };
