/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
  IsInt,
  Max,
  IsNumber,
} from "class-validator";

import { AppointmentServiceItemCreateNestedManyWithoutServiceEntitiesInput } from "./AppointmentServiceItemCreateNestedManyWithoutServiceEntitiesInput";
import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { ServiceStaffLinkCreateNestedManyWithoutServiceEntitiesInput } from "./ServiceStaffLinkCreateNestedManyWithoutServiceEntitiesInput";
import { StaffCustomServiceCreateNestedManyWithoutServiceEntitiesInput } from "./StaffCustomServiceCreateNestedManyWithoutServiceEntitiesInput";

@InputType()
class ServiceEntityCreateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  activo?: boolean | null;

  @ApiProperty({
    required: false,
    type: () =>
      AppointmentServiceItemCreateNestedManyWithoutServiceEntitiesInput,
  })
  @ValidateNested()
  @Type(() => AppointmentServiceItemCreateNestedManyWithoutServiceEntitiesInput)
  @IsOptional()
  @Field(
    () => AppointmentServiceItemCreateNestedManyWithoutServiceEntitiesInput,
    {
      nullable: true,
    }
  )
  appointmentServices?: AppointmentServiceItemCreateNestedManyWithoutServiceEntitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoria?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descripcion?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  duracionBaseMinutos?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  precioBase?: Decimal | null;

  @ApiProperty({
    required: false,
    type: () => ServiceStaffLinkCreateNestedManyWithoutServiceEntitiesInput,
  })
  @ValidateNested()
  @Type(() => ServiceStaffLinkCreateNestedManyWithoutServiceEntitiesInput)
  @IsOptional()
  @Field(() => ServiceStaffLinkCreateNestedManyWithoutServiceEntitiesInput, {
    nullable: true,
  })
  serviceStaffLinks?: ServiceStaffLinkCreateNestedManyWithoutServiceEntitiesInput;

  @ApiProperty({
    required: false,
    type: () => StaffCustomServiceCreateNestedManyWithoutServiceEntitiesInput,
  })
  @ValidateNested()
  @Type(() => StaffCustomServiceCreateNestedManyWithoutServiceEntitiesInput)
  @IsOptional()
  @Field(() => StaffCustomServiceCreateNestedManyWithoutServiceEntitiesInput, {
    nullable: true,
  })
  staffCustomServices?: StaffCustomServiceCreateNestedManyWithoutServiceEntitiesInput;
}

export { ServiceEntityCreateInput as ServiceEntityCreateInput };
