/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Service as PrismaService,
  AppointmentService as PrismaAppointmentService,
  ServiceStaffType as PrismaServiceStaffType,
  StaffServiceCustom as PrismaStaffServiceCustom,
} from "@prisma/client";

export class ServiceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ServiceCountArgs, "select">): Promise<number> {
    return this.prisma.service.count(args);
  }

  async services(args: Prisma.ServiceFindManyArgs): Promise<PrismaService[]> {
    return this.prisma.service.findMany(args);
  }
  async service(
    args: Prisma.ServiceFindUniqueArgs
  ): Promise<PrismaService | null> {
    return this.prisma.service.findUnique(args);
  }
  async createService(args: Prisma.ServiceCreateArgs): Promise<PrismaService> {
    return this.prisma.service.create(args);
  }
  async updateService(args: Prisma.ServiceUpdateArgs): Promise<PrismaService> {
    return this.prisma.service.update(args);
  }
  async deleteService(args: Prisma.ServiceDeleteArgs): Promise<PrismaService> {
    return this.prisma.service.delete(args);
  }

  async findAppointmentServices(
    parentId: string,
    args: Prisma.AppointmentServiceFindManyArgs
  ): Promise<PrismaAppointmentService[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .appointmentServices(args);
  }

  async findServiceStaffTypes(
    parentId: string,
    args: Prisma.ServiceStaffTypeFindManyArgs
  ): Promise<PrismaServiceStaffType[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .serviceStaffTypes(args);
  }

  async findStaffServiceCustom(
    parentId: string,
    args: Prisma.StaffServiceCustomFindManyArgs
  ): Promise<PrismaStaffServiceCustom[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .staffServiceCustom(args);
  }
}
