/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { AppointmentServiceListRelationFilter } from "../../appointmentService/base/AppointmentServiceListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { ServiceStaffTypeListRelationFilter } from "../../serviceStaffType/base/ServiceStaffTypeListRelationFilter";
import { StaffServiceCustomListRelationFilter } from "../../staffServiceCustom/base/StaffServiceCustomListRelationFilter";

@InputType()
class ServiceWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  activo?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => AppointmentServiceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AppointmentServiceListRelationFilter)
  @IsOptional()
  @Field(() => AppointmentServiceListRelationFilter, {
    nullable: true,
  })
  appointmentServices?: AppointmentServiceListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  categoria?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  createdAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  descripcion?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  duracionBaseMinutos?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DecimalNullableFilter,
  })
  @Type(() => DecimalNullableFilter)
  @IsOptional()
  @Field(() => DecimalNullableFilter, {
    nullable: true,
  })
  precioBase?: DecimalNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ServiceStaffTypeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ServiceStaffTypeListRelationFilter)
  @IsOptional()
  @Field(() => ServiceStaffTypeListRelationFilter, {
    nullable: true,
  })
  serviceStaffTypes?: ServiceStaffTypeListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => StaffServiceCustomListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StaffServiceCustomListRelationFilter)
  @IsOptional()
  @Field(() => StaffServiceCustomListRelationFilter, {
    nullable: true,
  })
  staffServiceCustom?: StaffServiceCustomListRelationFilter;
}

export { ServiceWhereInput as ServiceWhereInput };
